.gitattributes
.gitignore
3rdparty/msinttypes/include/inttypes.h
3rdparty/msinttypes/include/stdint.h
3rdparty/mt19937ar/Makefile.in
3rdparty/mt19937ar/mt19937ar.c
3rdparty/mt19937ar/mt19937ar.h
3rdparty/mysql/include/atomic/gcc_builtins.h
3rdparty/mysql/include/atomic/generic-msvc.h
3rdparty/mysql/include/atomic/nolock.h
3rdparty/mysql/include/atomic/rwlock.h
3rdparty/mysql/include/atomic/x86-gcc.h
3rdparty/mysql/include/base64.h
3rdparty/mysql/include/config-win.h
3rdparty/mysql/include/decimal.h
3rdparty/mysql/include/errmsg.h
3rdparty/mysql/include/hash.h
3rdparty/mysql/include/keycache.h
3rdparty/mysql/include/lf.h
3rdparty/mysql/include/m_ctype.h
3rdparty/mysql/include/m_string.h
3rdparty/mysql/include/my_aes.h
3rdparty/mysql/include/my_alarm.h
3rdparty/mysql/include/my_alloc.h
3rdparty/mysql/include/my_atomic.h
3rdparty/mysql/include/my_attribute.h
3rdparty/mysql/include/my_base.h
3rdparty/mysql/include/my_bit.h
3rdparty/mysql/include/my_bitmap.h
3rdparty/mysql/include/my_charsets.h
3rdparty/mysql/include/my_config.h
3rdparty/mysql/include/my_dbug.h
3rdparty/mysql/include/my_dir.h
3rdparty/mysql/include/my_getopt.h
3rdparty/mysql/include/my_global.h
3rdparty/mysql/include/my_libwrap.h
3rdparty/mysql/include/my_list.h
3rdparty/mysql/include/my_md5.h
3rdparty/mysql/include/my_net.h
3rdparty/mysql/include/my_no_pthread.h
3rdparty/mysql/include/my_nosys.h
3rdparty/mysql/include/my_pthread.h
3rdparty/mysql/include/my_stacktrace.h
3rdparty/mysql/include/my_sys.h
3rdparty/mysql/include/my_time.h
3rdparty/mysql/include/my_tree.h
3rdparty/mysql/include/my_trie.h
3rdparty/mysql/include/my_uctype.h
3rdparty/mysql/include/my_vle.h
3rdparty/mysql/include/my_xml.h
3rdparty/mysql/include/myisampack.h
3rdparty/mysql/include/mysql.h
3rdparty/mysql/include/mysql_com.h
3rdparty/mysql/include/mysql_time.h
3rdparty/mysql/include/mysql_version.h
3rdparty/mysql/include/mysqld_error.h
3rdparty/mysql/include/mysys/rijndael.h
3rdparty/mysql/include/mysys_err.h
3rdparty/mysql/include/queues.h
3rdparty/mysql/include/service_versions.h
3rdparty/mysql/include/sha1.h
3rdparty/mysql/include/sha2.h
3rdparty/mysql/include/sql_common.h
3rdparty/mysql/include/sslopt-case.h
3rdparty/mysql/include/sslopt-longopts.h
3rdparty/mysql/include/sslopt-vars.h
3rdparty/mysql/include/t_ctype.h
3rdparty/mysql/include/thr_alarm.h
3rdparty/mysql/include/thr_lock.h
3rdparty/mysql/include/typelib.h
3rdparty/mysql/include/violite.h
3rdparty/mysql/include/waiting_threads.h
3rdparty/mysql/include/wqueue.h
3rdparty/mysql/lib/libmysql.dll
3rdparty/mysql/lib/libmysql.lib
3rdparty/mysql/lib/mysqlclient.lib
3rdparty/pcre/include/pcre.h
3rdparty/pcre/lib/libpcre.dll.a
3rdparty/pcre/lib/pcre.lib
3rdparty/zlib/include/zconf.h
3rdparty/zlib/include/zlib.h
3rdparty/zlib/lib/zdll.lib
3rdparty/zlib/lib/zlib.def
LICENSE
Makefile.in
README.md
char-server.sh
charserv-sql.bat
conf/atcommand_athena.conf
conf/battle/battle.conf
conf/battle/battleground.conf
conf/battle/client.conf
conf/battle/drops.conf
conf/battle/exp.conf
conf/battle/feature.conf
conf/battle/gm.conf
conf/battle/guild.conf
conf/battle/homunc.conf
conf/battle/items.conf
conf/battle/misc.conf
conf/battle/monster.conf
conf/battle/party.conf
conf/battle/pet.conf
conf/battle/player.conf
conf/battle/skill.conf
conf/battle/status.conf
conf/battle_athena.conf
conf/char_athena.conf
conf/charhelp.txt
conf/grf-files.txt
conf/help.txt
conf/help2.txt
conf/import/atcommand_conf.txt
conf/import/battle_conf.txt
conf/import/char_conf.txt
conf/import/inter_conf.txt
conf/import/log_conf.txt
conf/import/login_conf.txt
conf/import/map_conf.txt
conf/import/msg_conf.txt
conf/import/packet_conf.txt
conf/import/script_conf.txt
conf/inter_athena.conf
conf/log_athena.conf
conf/login_athena.conf
conf/map_athena.conf
conf/mapflag/battleground.txt
conf/mapflag/fireworks.txt
conf/mapflag/gvg.txt
conf/mapflag/jail.txt
conf/mapflag/night.txt
conf/mapflag/nightmare.txt
conf/mapflag/nobranch.txt
conf/mapflag/noexp.txt
conf/mapflag/noicewall.txt
conf/mapflag/noloot.txt
conf/mapflag/nomemo.txt
conf/mapflag/nopenalty.txt
conf/mapflag/nopvp.txt
conf/mapflag/noreturn.txt
conf/mapflag/nosave.txt
conf/mapflag/noskill.txt
conf/mapflag/noteleport.txt
conf/mapflag/novending.txt
conf/mapflag/nowarp.txt
conf/mapflag/nowarpto.txt
conf/mapflag/partylock.txt
conf/mapflag/pvp.txt
conf/mapflag/pvp_noguild.txt
conf/mapflag/pvp_noparty.txt
conf/mapflag/reset.txt
conf/mapflag/restricted.txt
conf/mapflag/town.txt
conf/maps_athena.conf
conf/motd.txt
conf/msg_athena.conf
conf/packet_athena.conf
conf/plugin_athena.conf
conf/readme.txt
conf/script_athena.conf
conf/subnet_athena.conf
configure
configure.in
db/Changelog.txt
db/abra_db.txt
db/attr_fix.txt
db/castle_db.txt
db/const.txt
db/create_arrow_db.txt
db/exp.txt
db/exp2.txt
db/exp_guild.txt
db/exp_homun.txt
db/guild_skill_tree.txt
db/homun_skill_tree.txt
db/homunculus_db.txt
db/item_avail.txt
db/item_bluebox.txt
db/item_buyingstore.txt
db/item_cardalbum.txt
db/item_cookie_bag.txt
db/item_db.txt
db/item_db2.txt
db/item_delay.txt
db/item_findingore.txt
db/item_giftbox.txt
db/item_group_db.txt
db/item_misc.txt
db/item_noequip.txt
db/item_scroll.txt
db/item_trade.txt
db/item_violetbox.txt
db/job_db1.txt
db/job_db2.txt
db/map_cache.dat
db/map_index.txt
db/mercenary_db.txt
db/mercenary_skill_db.txt
db/mob_avail.txt
db/mob_boss.txt
db/mob_branch.txt
db/mob_chat_db.txt
db/mob_db.txt
db/mob_db2.txt
db/mob_poring.txt
db/mob_pouch.txt
db/mob_race2_db.txt
db/mob_skill_db.txt
db/mob_skill_db2.txt
db/packet_db.txt
db/pet_db.txt
db/pet_db2.txt
db/produce_db.txt
db/quest_db.txt
db/refine_db.txt
db/size_fix.txt
db/skill_cast_db.txt
db/skill_castnodex_db.txt
db/skill_db.txt
db/skill_nocast_db.txt
db/skill_require_db.txt
db/skill_tree.txt
db/skill_unit_db.txt
db/statpoint.txt
dbghelp.dll
eAthena-11.sln
libmysql.dll
login-server.sh
logserv-sql.bat
map-server.sh
mapserv-sql.bat
npc/airports/airships.txt
npc/airports/einbroch.txt
npc/airports/lighthalzen.txt
npc/airports/yuno.txt
npc/battleground/bg_common.txt
npc/battleground/flavius/flavius01.txt
npc/battleground/flavius/flavius02.txt
npc/battleground/flavius/flavius_enter.txt
npc/battleground/kvm/kvm01.txt
npc/battleground/kvm/kvm02.txt
npc/battleground/kvm/kvm03.txt
npc/battleground/kvm/kvm_enter.txt
npc/battleground/kvm/kvm_item_pay.txt
npc/battleground/tierra/tierra01.txt
npc/battleground/tierra/tierra02.txt
npc/battleground/tierra/tierra_enter.txt
npc/cities/alberta.txt
npc/cities/aldebaran.txt
npc/cities/amatsu.txt
npc/cities/ayothaya.txt
npc/cities/brasilis.txt
npc/cities/comodo.txt
npc/cities/einbech.txt
npc/cities/einbroch.txt
npc/cities/geffen.txt
npc/cities/gonryun.txt
npc/cities/hugel.txt
npc/cities/izlude.txt
npc/cities/jawaii.txt
npc/cities/lighthalzen.txt
npc/cities/louyang.txt
npc/cities/lutie.txt
npc/cities/manuk.txt
npc/cities/morocc.txt
npc/cities/moscovia.txt
npc/cities/niflheim.txt
npc/cities/payon.txt
npc/cities/prontera.txt
npc/cities/rachel.txt
npc/cities/splendide.txt
npc/cities/umbala.txt
npc/cities/veins.txt
npc/cities/yuno.txt
npc/custom/2-2shop.txt
npc/custom/Lance/FR_HallOfFame.c
npc/custom/Lance/FR_MailSystem.c
npc/custom/Lance/FR_WeatherController.c
npc/custom/MVP_arena/amvp_func.txt
npc/custom/MVP_arena/arena_mvp.txt
npc/custom/WoE_Setter.txt
npc/custom/airplane.txt
npc/custom/ayothaya.txt
npc/custom/banks/bank.txt
npc/custom/banks/kafra_bank.txt
npc/custom/battleground/bg_common.txt
npc/custom/battleground/bg_flavius_01.txt
npc/custom/battleground/bg_flavius_02.txt
npc/custom/battleground/bg_kvm01.txt
npc/custom/battleground/bg_kvm02.txt
npc/custom/battleground/bg_kvm03.txt
npc/custom/battleground/bg_tierra_01.txt
npc/custom/battleground/bg_tierra_02.txt
npc/custom/blackjack.txt
npc/custom/breeder.txt
npc/custom/card_remover.txt
npc/custom/devnpc.txt
npc/custom/dye.txt
npc/custom/eAAC_Scripts/DonationGirl/donate.txt
npc/custom/eAAC_Scripts/DonationGirl/sql/donate.sql
npc/custom/eAAC_Scripts/DonationGirl/sql/donate_item_db.sql
npc/custom/eAAC_Scripts/Kafra_Express_files.conf
npc/custom/eAAC_Scripts/banker.txt
npc/custom/eAAC_Scripts/kafraExpress/Changelog.txt
npc/custom/eAAC_Scripts/kafraExpress/config.txt
npc/custom/eAAC_Scripts/kafraExpress/global_functionsKE.txt
npc/custom/eAAC_Scripts/kafraExpress/kafras.txt
npc/custom/eAAC_Scripts/kafraExpress/ke_bank.txt
npc/custom/eAAC_Scripts/kafraExpress/ke_broadcast.txt
npc/custom/eAAC_Scripts/kafraExpress/ke_dye.txt
npc/custom/eAAC_Scripts/kafraExpress/ke_jobchange.txt
npc/custom/eAAC_Scripts/kafraExpress/ke_jobswap.txt
npc/custom/eAAC_Scripts/kafraExpress/ke_main.txt
npc/custom/eAAC_Scripts/kafraExpress/ke_refine.txt
npc/custom/eAAC_Scripts/kafraExpress/ke_rent.txt
npc/custom/eAAC_Scripts/kafraExpress/ke_shop.txt
npc/custom/eAAC_Scripts/kafraExpress/ke_statmarket.txt
npc/custom/eAAC_Scripts/kafraExpress/ke_stats.txt
npc/custom/eAAC_Scripts/kafraExpress/ke_uncard.txt
npc/custom/eAAC_Scripts/kafraExpress/ke_warp_dungeon.txt
npc/custom/eAAC_Scripts/kafraExpress/ke_warp_pvp.txt
npc/custom/eAAC_Scripts/kafraExpress/ke_warp_town.txt
npc/custom/eAAC_Scripts/kafraExpress/ke_warp_woe.txt
npc/custom/eAAC_Scripts/kafraExpress/readme.txt
npc/custom/eAAC_Scripts/messageboards.txt
npc/custom/eAAC_Scripts/quest_warper.txt
npc/custom/eAAC_Scripts/roll_a_dice.txt
npc/custom/eAAC_Scripts/vendmachine.txt
npc/custom/events/2006_dogs_year.txt
npc/custom/events/draculax.txt
npc/custom/events/hallow06.txt
npc/custom/events/hyegun_event.txt
npc/custom/events/kings_items.txt
npc/custom/events/p_track/p_track_core.txt
npc/custom/events/p_track/p_track_warpers.txt
npc/custom/events/uneasy_cemetery.txt
npc/custom/events/valentinesdayexp.txt
npc/custom/events/xmas_rings_event.txt
npc/custom/floating_rates.txt
npc/custom/healers/heal.txt
npc/custom/healers/heal_payment.txt
npc/custom/jobs/jobmaster.txt
npc/custom/jobs/reset.txt
npc/custom/lottery.txt
npc/custom/market.txt
npc/custom/marriage.txt
npc/custom/morroc_raceway.txt
npc/custom/mvm.txt
npc/custom/penal_servitude.txt
npc/custom/platinum_skills.txt
npc/custom/quests/bandit_beard.txt
npc/custom/quests/berzebub.txt
npc/custom/quests/bongunsword.txt
npc/custom/quests/bookofthedevil.txt
npc/custom/quests/dead_branch.txt
npc/custom/quests/elvenear.txt
npc/custom/quests/event_6_new_hats.txt
npc/custom/quests/fashion.txt
npc/custom/quests/ironcane.txt
npc/custom/quests/kaho_balmung.txt
npc/custom/quests/kahohorn.txt
npc/custom/quests/kiel_quest.txt
npc/custom/quests/lvl99_quest.txt
npc/custom/quests/magicalhatquest.txt
npc/custom/quests/may_hats.txt
npc/custom/quests/sphinx_mask.txt
npc/custom/quests/sunglasses.txt
npc/custom/quests/tha_statues.txt
npc/custom/quests/thq/THQS_ChatingNPC.txt
npc/custom/quests/thq/THQS_GuildNPC.txt
npc/custom/quests/thq/THQS_QuestNPC.txt
npc/custom/quests/thq/THQS_Quests.txt
npc/custom/quests/thq/THQS_TTShop.txt
npc/custom/quests/umbalian_language.txt
npc/custom/quests/valhallen.txt
npc/custom/rpsroulette.txt
npc/custom/shifty_assassin.txt
npc/custom/sign_your_items.txt
npc/custom/stock_market.txt
npc/custom/warper.txt
npc/events/MemorialDay_2008.txt
npc/events/StPatrick_2008.txt
npc/events/children_week.txt
npc/events/christmas_2005.txt
npc/events/christmas_2008.txt
npc/events/dumplingfestival.txt
npc/events/easter.txt
npc/events/easter_2008.txt
npc/events/event_skill_reset.txt
npc/events/gdevent_aru.txt
npc/events/gdevent_sch.txt
npc/events/god_se_festival.txt
npc/events/halloween_2006.txt
npc/events/halloween_2008.txt
npc/events/halloween_2009.txt
npc/events/idul_fitri.txt
npc/events/lunar_2008.txt
npc/events/nguild/nguild_dunsw.txt
npc/events/nguild/nguild_ev_agit.txt
npc/events/nguild/nguild_flags.txt
npc/events/nguild/nguild_guardians.txt
npc/events/nguild/nguild_kafras.txt
npc/events/nguild/nguild_managers.txt
npc/events/nguild/nguild_treas.txt
npc/events/nguild/nguild_warper.txt
npc/events/twintowers.txt
npc/events/valentinesday.txt
npc/events/valentinesday_2009.txt
npc/events/whiteday.txt
npc/events/xmas.txt
npc/guides/guides_alb.txt
npc/guides/guides_alde.txt
npc/guides/guides_ama.txt
npc/guides/guides_ayo.txt
npc/guides/guides_brasilis.txt
npc/guides/guides_cmd.txt
npc/guides/guides_einbe.txt
npc/guides/guides_einbr.txt
npc/guides/guides_gef.txt
npc/guides/guides_gon.txt
npc/guides/guides_hu.txt
npc/guides/guides_izl.txt
npc/guides/guides_juno.txt
npc/guides/guides_lhz.txt
npc/guides/guides_louyang.txt
npc/guides/guides_moc.txt
npc/guides/guides_mosk.txt
npc/guides/guides_nif.txt
npc/guides/guides_pay.txt
npc/guides/guides_pron.txt
npc/guides/guides_rachel.txt
npc/guides/guides_um.txt
npc/guides/guides_veins.txt
npc/guild/agit_controller.txt
npc/guild/agit_template.txt
npc/guild/aldeg_cas01.txt
npc/guild/aldeg_cas02.txt
npc/guild/aldeg_cas03.txt
npc/guild/aldeg_cas04.txt
npc/guild/aldeg_cas05.txt
npc/guild/gefg_cas01.txt
npc/guild/gefg_cas02.txt
npc/guild/gefg_cas03.txt
npc/guild/gefg_cas04.txt
npc/guild/gefg_cas05.txt
npc/guild/payg_cas01.txt
npc/guild/payg_cas02.txt
npc/guild/payg_cas03.txt
npc/guild/payg_cas04.txt
npc/guild/payg_cas05.txt
npc/guild/prtg_cas01.txt
npc/guild/prtg_cas02.txt
npc/guild/prtg_cas03.txt
npc/guild/prtg_cas04.txt
npc/guild/prtg_cas05.txt
npc/guild2/agit_start_se.txt
npc/guild2/arug_cas01.txt
npc/guild2/arug_cas02.txt
npc/guild2/arug_cas03.txt
npc/guild2/arug_cas04.txt
npc/guild2/arug_cas05.txt
npc/guild2/guild_dungeon.txt
npc/guild2/guild_flags.txt
npc/guild2/schg_cas01.txt
npc/guild2/schg_cas02.txt
npc/guild2/schg_cas03.txt
npc/guild2/schg_cas04.txt
npc/guild2/schg_cas05.txt
npc/instances/EndlessTower.txt
npc/instances/NydhoggsNest.txt
npc/instances/OrcsMemory.txt
npc/instances/SealedShrine.txt
npc/jobs/1-1/acolyte.txt
npc/jobs/1-1/archer.txt
npc/jobs/1-1/mage.txt
npc/jobs/1-1/merchant.txt
npc/jobs/1-1/swordman.txt
npc/jobs/1-1/thief.txt
npc/jobs/1-1e/gunslinger.txt
npc/jobs/1-1e/ninja.txt
npc/jobs/1-1e/taekwon.txt
npc/jobs/2-1/assassin.txt
npc/jobs/2-1/blacksmith.txt
npc/jobs/2-1/hunter.txt
npc/jobs/2-1/knight.txt
npc/jobs/2-1/priest.txt
npc/jobs/2-1/wizard.txt
npc/jobs/2-1a/AssassinCross.txt
npc/jobs/2-1a/HighPriest.txt
npc/jobs/2-1a/HighWizard.txt
npc/jobs/2-1a/LordKnight.txt
npc/jobs/2-1a/Sniper.txt
npc/jobs/2-1a/WhiteSmith.txt
npc/jobs/2-1e/StarGladiator.txt
npc/jobs/2-2/alchemist.txt
npc/jobs/2-2/bard.txt
npc/jobs/2-2/crusader.txt
npc/jobs/2-2/dancer.txt
npc/jobs/2-2/monk.txt
npc/jobs/2-2/rogue.txt
npc/jobs/2-2/sage.txt
npc/jobs/2-2a/Champion.txt
npc/jobs/2-2a/Clown.txt
npc/jobs/2-2a/Creator.txt
npc/jobs/2-2a/Gypsy.txt
npc/jobs/2-2a/Paladin.txt
npc/jobs/2-2a/Professor.txt
npc/jobs/2-2a/Stalker.txt
npc/jobs/2-2e/SoulLinker.txt
npc/jobs/novice/novice.txt
npc/jobs/novice/supernovice.txt
npc/jobs/valkyrie.txt
npc/kafras/cool_event_corp.txt
npc/kafras/dts_warper.txt
npc/kafras/functions_kafras.txt
npc/kafras/kafras_alb.txt
npc/kafras/kafras_alde.txt
npc/kafras/kafras_brasilis.txt
npc/kafras/kafras_com.txt
npc/kafras/kafras_dungeons.txt
npc/kafras/kafras_gef.txt
npc/kafras/kafras_izl.txt
npc/kafras/kafras_mor.txt
npc/kafras/kafras_mosk.txt
npc/kafras/kafras_new.txt
npc/kafras/kafras_pay.txt
npc/kafras/kafras_pron.txt
npc/kafras/kafras_yun.txt
npc/merchants/advanced_refiner.txt
npc/merchants/alchemist.txt
npc/merchants/ammo_boxes.txt
npc/merchants/ammo_dealer.txt
npc/merchants/buying_shops.txt
npc/merchants/cash_hair.txt
npc/merchants/cash_trader.txt
npc/merchants/clothes_dyer.txt
npc/merchants/dye_maker.txt
npc/merchants/elemental_trader.txt
npc/merchants/enchan_arm.txt
npc/merchants/gemstone.txt
npc/merchants/hair_dyer.txt
npc/merchants/hair_style.txt
npc/merchants/icecream.txt
npc/merchants/inn.txt
npc/merchants/kunai_maker.txt
npc/merchants/manuk.txt
npc/merchants/milk_trader.txt
npc/merchants/novice_exchange.txt
npc/merchants/old_pharmacist.txt
npc/merchants/quivers.txt
npc/merchants/refine.txt
npc/merchants/renters.txt
npc/merchants/shops.txt
npc/merchants/socket_enchant.txt
npc/merchants/socket_enchant2.txt
npc/merchants/splendide.txt
npc/merchants/wander_pet_food.txt
npc/mobs/citycleaners.txt
npc/mobs/dungeons/abbey.txt
npc/mobs/dungeons/abyss.txt
npc/mobs/dungeons/alde_dun.txt
npc/mobs/dungeons/ama_dun.txt
npc/mobs/dungeons/anthell.txt
npc/mobs/dungeons/ayo_dun.txt
npc/mobs/dungeons/beach_dun.txt
npc/mobs/dungeons/bra_dun.txt
npc/mobs/dungeons/c_tower.txt
npc/mobs/dungeons/ein_dun.txt
npc/mobs/dungeons/gef_dun.txt
npc/mobs/dungeons/gefenia.txt
npc/mobs/dungeons/glastheim.txt
npc/mobs/dungeons/gld_dun.txt
npc/mobs/dungeons/gld_dunSE.txt
npc/mobs/dungeons/gon_dun.txt
np